export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const SIGNOUT = 'SIGNOUT';

export const FETCH_TODO = 'FETCH_TODO';
export const FETCH_TODO_START = 'FETCH_TODO_START';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
export const FETCH_TODO_FAIL = 'FETCH_TODO_FAIL';

export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const CHANGE_TODO_STATUS = 'CHANGE_TODO_STATUS';
export const COMPLETED_ALL_TODO = 'COMPLETED_ALL_TODO';
export const UNCOMPLETED_ALL_TODO = 'UNCOMPLETED_ALL_TODO';
export const CHANGE_TODO_FILTER = 'CHANGE_TODO_FILTER';  
